[package]
name = "pixel-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = "1.0.193"
serde_json = "1.0.108"
